### ISSUE TITLE
Less of an issue and more of a question from a No Code Salesforce Admin 

### ISSUE THREAD

**Issue by DMB28th** [bigassforce/statecodes#2]
On the last step (Modify) where you tell us to MASS activate all the values,  you tell us to use Force IDE or Workbench to run some code on an address.xml metadata.   I'm a bit confused on the specific steps here (I'm going through Workbench) and I have no idea where I'm supposed to go to complete this last step.  Can you give me a Step by Step in Workbench on what I'm supposed to click to complete this?  I'm sure it would be super helpful to all the other No code admins.  

Thanks!!!

**Comment by bigassforce** [comment]
Thanks for the ping. Here are the detailed steps:

1. Install the package in Sandbox, not production
2. Go to Installed Packages > Configure > Run Batch
3. Use any text editor to create a package.xml file:
    ```
    <?xml version="1.0" encoding="UTF-8"?>
    <Package>
        <types>
            <members>Address</members>
            <name>Settings</name>
        </types>
        <version>45.0</version>
    </Package>
    ```
3. In Workbench, go to Migration > Retrieve, use package.xml
4. Download the result and unzip its contents into a new folder
5. Open the Address.settings file in your text editor
6. Replace all `<active>false</active>` with `<active>true</active>`
7. Replace all `<visible>false</visible>` with `<visible>true</visible>`
8. Save changes, then zip up the exact contents of the folder again
9. In Workbench, go to Migration > Deploy, and deploy the new zip file

Kindly post a screenshot at the relevant step if you encounter any difficulties.

**Comment by bigassforce** [comment]
https://github.com/bigassforce/statecodes/issues/1#issuecomment-533122134
