### ISSUE TITLE
"invalid ISO code"

### ISSUE THREAD

**Issue by wcraig216** [bigassforce/statecodes#3]
When deploying to production ~ we're running into an issue where the isoCode on states is throwing an error like: "Invalid iso code 22 for state Nghệ An in country Viet Nam"
Ran batch in sandbox, retrieve, mass edit, deploy per the readme.

**Comment by bigassforce** [comment]
Thanks Will - please can you advise the value of the ISO Code and Integration Value before vs after the edit?

**Comment by wcraig216** [comment]
@bigassforce  This turned out to be my bad ~ tried to deploy values as active that had not yet been created. It seems you need to run your tool, extract, deploy, THEN switch active / visible.

Also ~ thank you for this tool ~ extremely helpful!
